### ISSUE TITLE
attribute error problem ??

### ISSUE THREAD

**Issue by CevreMuhendisi** [neuronalism/edxdlr#1]
Output directory: Downloaded
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\edxdlr-master\edxdlr.py", line 693, in <module>
    main()
  File "C:\Users\Admin\Desktop\edxdlr-master\edxdlr.py", line 688, in main
    download_course(args, course_block, headers, file_formats)
  File "C:\Users\Admin\Desktop\edxdlr-master\edxdlr.py", line 624, in download_course
    coursename = clean_filename(course_block.name)
  File "C:\Users\Admin\Desktop\edxdlr-master\utils.py", line 145, in clean_filename
    s = h.unescape(s)
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by neuronalism** [comment]
Are you using Python 3.9?  (if not plz let me know) 
You can try this patch first https://github.com/coursera-dl/edx-dl/commit/5490a99a98b56f544661c131229ef640ace2b064

If this patch works out for you, I'm glad to apply it to this code. Anyway my code is forked from original edx-dl project and therefore shares this problem too.

**Comment by neuronalism** [comment]
@CevreMuhendisi I updated the code to fix this issue, tested on 3.10.2 and it looked okay. It should be ok now on Python 3.9+, and i'm closing this issue.
If you encounter more issues with the updated code, feel free to start a new one.

**Comment by CevreMuhendisi** [comment]
thank you so much it worked
