### ISSUE TITLE
导入模块错误

### ISSUE THREAD

**Issue by chishichengyang** [neuronalism/edxdlr#10]
Import "six.moves.urllib.error" could not be resolved from source
我看文件夹也没有这个文件，想问一下是不是您忘了上传这个文件了？？？

**Comment by neuronalism** [comment]
这是第三方模块，你可能是这个模块没装上？重新试下 `pip install -r requirements.txt` 看看呢

**Comment by chishichengyang** [comment]
我换了环境装成功了
这份程序还是有点小问题，只能爬下课程的网页，不能转为pdf文件

**Comment by neuronalism** [comment]
确实没做html转pdf的，因为我不会|(*′口`)
