### ISSUE TITLE
too many folders

### ISSUE THREAD

**Issue by aliafshany** [neuronalism/edxdlr#4]
hi there,
i wanna thank you for this script. this was the only one which worked for me.

i'd like to make a suggestion.
this script creats too many unnecessary folders which is so frustrating to see a course this way. ( you haev to open many folders)

could you do something about it?

for example you can name activity files instead of creating another folder for ir.

best

**Comment by aliafshany** [comment]
it's just a sample i'm showing to you.

![image](https://user-images.githubusercontent.com/40741745/167284016-a7e8663a-63e4-40f4-9a2f-fb6b56a76576.png)
![image](https://user-images.githubusercontent.com/40741745/167284022-5a925087-1fe0-4440-9767-e5e34f375b8c.png)
![image](https://user-images.githubusercontent.com/40741745/167284028-2d81812d-e678-47ee-a45d-9d02c4070e6d.png)

**Comment by aliafshany** [comment]
oh and btw the scripts is so slow.
could you do sth about it also?

best

**Comment by aliafshany** [comment]
and also it doesn't download in 720p or higher resolutions.
it's 540 or less i guess.

could you do sth about it also?

**Comment by neuronalism** [comment]
> hi there, i wanna thank you for this script. this was the only one which worked for me.

Glad it can help you. 

> i'd like to make a suggestion. this script creats too many unnecessary folders which is so frustrating to see a course this way. ( you haev to open many folders)
> for example you can name activity files instead of creating another folder for ir.

I know it too, and personally I'm not satisfied with that as well. But I'm not proficient in python, and the courses that I tested on when editing the script had multiple videos and files in one page. The easiest way to make it run was to create more folders. I'll try to improve this if I have spare time. 

> oh and btw the scripts is so slow. could you do sth about it also?

The script is slow because it downloads everything in sequence. The bottleneck is video downloading. For reasons that I dont understand python multiprocessing does not run on my computer, so I have to delete that feature in the script.

> and also it doesn't download in 720p or higher resolutions.
> it's 540 or less i guess.

That's something I did not notice. Mind if I know which course so that I can check it?

**Comment by aliafshany** [comment]
First and foremost, I want to express my gratitude for responding to each issue and working to improve the script.

I can determine from the video quality and the android app, which displays the course's size based on video quality.

This course was 1.2 GB, and I believe I got 675 MB in 720p using the script.

link of the course:
[https://www.edx.org/course/ap-macroeconomics?index=product&queryID=5effdf796b3d473ffb374a666e382e76&position=1&queryID=5effdf796b3d473ffb374a666e382e](url)

**Comment by CevreMuhendisi** [comment]
Thank you for everthing @neuronalism

**Comment by neuronalism** [comment]
@aliafshany I tried this course, and one strange thing is that, I don't see any option on Web player that allow me to change the resolution. The script gets the same link to the video as my browser does, so honestly I don't know where the missing 600MB goes.

**Comment by aliafshany** [comment]
got it.
if you try to play a video there would be a .m3u8 file that everything is there.
![image](https://user-images.githubusercontent.com/40741745/167291893-52afc98f-f201-4242-89d4-695a6adca43a.png)

for example look at this.

[https://edx-video.net/DVDDXN02T314-L010204/DVDDXN02T314-L010204_1_.m3u8
](url)
this is the link for this video:
![image](https://user-images.githubusercontent.com/40741745/167291825-79366e19-ce7a-4770-a5e2-21864bfad6e2.png)


this is the picture of  the downloaded file from the script:
![image](https://user-images.githubusercontent.com/40741745/167291876-3061ab68-0290-4fe1-9fe7-51d65a874e7c.png)


if you try to download this .m3u8 with yt-dlp you will get this one instead (89 MB):
![image](https://user-images.githubusercontent.com/40741745/167291932-d4eb7abd-5bf5-4e78-940f-1dbc497ee589.png)

**Comment by aliafshany** [comment]
in a simple way, if you try to download .m3u8 file instead of grabbing "Download video file" button, the problem would be solved easily.

**Comment by neuronalism** [comment]
ahhh i see. need another module to process m3u8 then. working on it.

**Comment by aliafshany** [comment]
i appreciate your time and effort🌺

**Comment by neuronalism** [comment]
@aliafshany I added another option `--download-m3u8`, which downloads max resolution file. Also file naming got improved. 

> oh and btw the scripts is so slow.
> could you do sth about it also?

I think this is the only issue which I have no solution for at the moment. I may close this issue for now.
