### ISSUE TITLE
课程只下载了网页。没有下载视频和课件材料

### ISSUE THREAD

**Issue by weightliftingecon** [neuronalism/edxdlr#8]
我下载了两门课，其中一门课件和视频都有，但另外一门只下载了网页的镜面，求求大神debug.帮俺看看

**Comment by Twstar-a** [comment]
> I downloaded two courses, one of which has courseware and video, but the other only downloaded the mirror of the web page, please help me to find out

@susantoplane @neuronalism 
Hi..is this fixed? I am not able to download videos as well. Just the course structure

**Comment by weightliftingecon** [comment]
> 

hey i believe it's still unfixed.  I encountered the same issue

**Comment by neuronalism** [comment]
> > 
> 
> hey i believe it's still unfixed. I encountered the same issue

有课程链接吗？我看下

**Comment by neuronalism** [comment]
> > I downloaded two courses, one of which has courseware and video, but the other only downloaded the mirror of the web page, please help me to find out
> 
> @susantoplane @neuronalism Hi..is this fixed? I am not able to download videos as well. Just the course structure

do you have the link or course-ID? I'll check it out.

**Comment by neuronalism** [comment]
> 我下载了两门课，其中一门课件和视频都有，但另外一门只下载了网页的镜面，求求大神debug.帮俺看看

我随便找了门课试了下，发现edx又改版了（苦笑）修改了一下code，你可以试下新的版本。

**Comment by neuronalism** [comment]
This issue seems fixed. I'll close this. If you have more problems, you may start a new issue.
