### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by aadimator** [neuronalism/edxdlr#9]
I'm getting the following error. 

![image](https://github.com/neuronalism/edxdlr/assets/10383542/dfa93310-62c6-47a3-903f-29bb15ebbdc8)

Any idea why this might be happening or what I should try?

**Comment by neuronalism** [comment]
400 response, to my knowledge, is most commonly due to incorrect username or password. I just updated the code to print out the specific error info, so that you can check it out. You may try the updated code and see if more errors show up (hope not).

**Comment by aadimator** [comment]
Many thanks. That helped me to figure out the problem.
